name: pet_tag_app
description: Pet Tag Manager Flutter App
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true