
name: pet_tag_pro
description: Pet Tag Tracking App
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  mobile_scanner: ^3.5.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
